# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']

  - job_name: 'pro'
    scrape_interval: 1s
    static_configs:
      - targets:
        - pro:7070

  - job_name: 'rec'
    scrape_interval: 1s
    static_configs:
      - targets:
        - rec:7070

  - job_name: 'rev'
    scrape_interval: 1s
    static_configs:
      - targets:
        - rev:7070

  - job_name: 'composite'
    scrape_interval: 1s
    static_configs:
      - targets:
        - composite:7070
