server:
  port: 0

info:
  component: Product Core Service

service:
  defaultMinMs: 5
  defaultMaxMs: 20

logging:
  level:
    root: WARN

    # Get info on failed OAuth access token validations
    org.springframework.boot.autoconfigure.security.oauth2.resource.UserInfoTokenServices: INFO

    # Get info regarding connection to the cofig server and retries if required
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: INFO
    org.springframework.retry.support.RetryTemplate: DEBUG

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO

    # Set DEBUG level on Hystrix to get an error message when a fallback method is used.
    com.netflix.hystrix: DEBUG
    com.netflix.hystrix.strategy.properties.HystrixPropertiesChainedArchaiusProperty: WARN
    se.callista: INFO



ribbon:
  # Interval to refresh the server list from the source
  serverListRefreshInterval: 1000
#
#  # Connect timeout used by Apache HttpClient
#  connectTimeout: 100
#
#  # Read timeout used by Apache HttpClient
#  readTimeout: 10000

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
    registryFetchIntervalSeconds: 1
    instanceInfoReplicationIntervalSeconds: 1
    initialInstanceInfoReplicationIntervalSeconds: 1

---
# For deployment in Docker containers
spring:
  profiles: docker

server:
  port: 8080

app:
  rabbitmq:
    host: rabbitmq

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

---
# For deployment in Cloud Foundry
spring:
  profiles: cloud

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: http://ml-public-ds-1.cfapps.io/eureka/
