---
# For deployment in Docker containers
spring:
  profiles: docker

  rabbitmq.host: rabbitmq

  data.mongodb.uri: mongodb://mongodb:27017/recommendation-db

server.port: 8080

---
# For development
spring:
  profiles: development

  cloud.discovery.enabled: false

  rabbitmq.host: localhost

# 1.0 means 100%, see http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_sampling
spring.sleuth.sampler.percentage: 1.0

logging:
  level:
    root: INFO
    se.callista: WARN
    org.springframework.data: INFO

server.port: 8082
